### ISSUE TITLE
When a player disconnects there are duplicate "left the game" messages with their combat logger

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/CivChat2#21]
When a player disconnects "player left the game". Then "player joined the game" from their combat logger, and when their combat logger disappears "player left the game". This makes it hard to actually know if a player is in game or not

**Comment by Maxopoly** [comment]
Is this from the actual thing we built into CivChat or just Skynet?

**Comment by wingzero54** [comment]
Oh you're right this is Skynet, I go back and forth between clients and didn't even realize that. Okay this can be closed then, outside mod issue
