### ISSUE TITLE
Rename global chat to local chat

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/CivChat2#26]
It is confusing that the local proximity chat is referred to as "global" chat when it's not global, it's local chat. Especially since we've officially endorsed ! as the global chat group

**Comment by wingzero54** [comment]
Should be solved with [this PR](https://github.com/CivClassic/CivChat2/pull/27)

**Comment by Maxopoly** [comment]
Implemented by https://github.com/CivClassic/CivChat2/issues/26
