### ISSUE TITLE
1.14: "You are now chatting with ..." formatting broken

### ISSUE THREAD

**Issue by Diet-Cola** [CivClassic/CivChat2#3]
![image](https://user-images.githubusercontent.com/12645603/72354550-e4a65600-36dd-11ea-859c-4a38952f5efb.png)

**Comment by Diet-Cola** [comment]
Also expands to formatting for error messages such as "There is no group with that name"

**Comment by Maxopoly** [comment]
Fixed in https://github.com/CivClassic/CivChat2/commit/d5dca7e619c5043b04bcbe46e2d08229a3cf0621
