### ISSUE TITLE
Ignoring groups is broken

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/CivChat2#8]
> It seems /ignoregroup no longer works. Before the update I was ignoring the ! global chat group. When I type /ignorelist it comes up as one of my ignored groups. However, when I try to un-ignore it (using the command /ignore !) I get a "command not available" error. This is the command listed in the /help menu.

Group/player ignoring should be reworked entirely into /config settings, code for that can be stolen from JukeAlerts group ignoring.

**Comment by Diet-Cola** [comment]
#9 

For the mean time fixes existing functionality

**Comment by Maxopoly** [comment]
Partially fixed and superceded by https://github.com/CivClassic/CivChat2/issues/10
